dbfilename redis_cache.rdb
dir /home/iicc2/business-mgm/config/pids
pidfile /home/iicc2/business-mgm/config/pids/redis_cache.pid
bind 127.0.0.1
port 13002
maxmemory 190mb
maxmemory-policy allkeys-lru
appendonly no

save ""


aclfile /home/iicc2/business-mgm/config/redis_cache.acl
