dbfilename redis_queue.rdb
dir /home/iicc2/business-mgm/config/pids
pidfile /home/iicc2/business-mgm/config/pids/redis_queue.pid
bind 127.0.0.1
port 11002

aclfile /home/iicc2/business-mgm/config/redis_queue.acl
