dbfilename redis_socketio.rdb
dir /home/iicc2/umrah-mgmt/config/pids
pidfile /home/iicc2/umrah-mgmt/config/pids/redis_socketio.pid
bind 127.0.0.1
port 12002

aclfile /home/iicc2/umrah-mgmt/config/redis_socketio.acl
