dbfilename redis_queue.rdb
dir /home/frappe/frappe/umrah-mgmt/config/pids
pidfile /home/frappe/frappe/umrah-mgmt/config/pids/redis_queue.pid
bind 127.0.0.1
port 11002

aclfile /home/frappe/frappe/umrah-mgmt/config/redis_queue.acl
