; Notes:
; priority=1 --> Lower priorities indicate programs that start first and shut down last
; killasgroup=true --> send kill signal to child processes too

; graceful timeout should always be lower than stopwaitsecs to avoid orphan gunicorn workers.
[program:umrah-mgmt-umrah-web]
command=/home/iicc2/umrah-mgmt/env/bin/gunicorn -b 127.0.0.1:8000 -w 9 --max-requests 5000 --max-requests-jitter 500 -t 120 --graceful-timeout 30 frappe.app:application --preload
priority=4
autostart=true
autorestart=true
stdout_logfile=/home/iicc2/umrah-mgmt/logs/web.log
stderr_logfile=/home/iicc2/umrah-mgmt/logs/web.error.log
stopwaitsecs=40
killasgroup=true
user=iicc2
directory=/home/iicc2/umrah-mgmt/sites
startretries=10

[program:umrah-mgmt-umrah-schedule]
command=/home/iicc2/.local/bin/bench schedule
priority=3
autostart=true
autorestart=true
stdout_logfile=/home/iicc2/umrah-mgmt/logs/schedule.log
stderr_logfile=/home/iicc2/umrah-mgmt/logs/schedule.error.log
user=iicc2
directory=/home/iicc2/umrah-mgmt
startretries=10

[program:umrah-mgmt-umrah-short-worker]
command=/home/iicc2/.local/bin/bench worker --queue short,default
priority=4
autostart=true
autorestart=true
stdout_logfile=/home/iicc2/umrah-mgmt/logs/worker.log
stderr_logfile=/home/iicc2/umrah-mgmt/logs/worker.error.log
user=iicc2
stopwaitsecs=360
directory=/home/iicc2/umrah-mgmt
killasgroup=true
numprocs=1
process_name=%(program_name)s-%(process_num)d
startretries=10

[program:umrah-mgmt-umrah-long-worker]
command=/home/iicc2/.local/bin/bench worker --queue long,default,short
priority=4
autostart=true
autorestart=true
stdout_logfile=/home/iicc2/umrah-mgmt/logs/worker.log
stderr_logfile=/home/iicc2/umrah-mgmt/logs/worker.error.log
user=iicc2
stopwaitsecs=1560
directory=/home/iicc2/umrah-mgmt
killasgroup=true
numprocs=1
process_name=%(program_name)s-%(process_num)d
startretries=10

[program:umrah-mgmt-redis-cache]
command=/usr/bin/redis-server /home/iicc2/umrah-mgmt/config/redis_cache.conf
priority=1
autostart=true
autorestart=true
stdout_logfile=/home/iicc2/umrah-mgmt/logs/redis-cache.log
stderr_logfile=/home/iicc2/umrah-mgmt/logs/redis-cache.error.log
user=iicc2
directory=/home/iicc2/umrah-mgmt/sites
startretries=10

[program:umrah-mgmt-redis-queue]
command=/usr/bin/redis-server /home/iicc2/umrah-mgmt/config/redis_queue.conf
priority=1
autostart=true
autorestart=true
stdout_logfile=/home/iicc2/umrah-mgmt/logs/redis-queue.log
stderr_logfile=/home/iicc2/umrah-mgmt/logs/redis-queue.error.log
user=iicc2
directory=/home/iicc2/umrah-mgmt/sites
startretries=10

[program:umrah-mgmt-redis-socketio]
command=/usr/bin/redis-server /home/iicc2/umrah-mgmt/config/redis_socketio.conf
priority=1
autostart=true
autorestart=true
stdout_logfile=/home/iicc2/umrah-mgmt/logs/redis-socketio.log
stderr_logfile=/home/iicc2/umrah-mgmt/logs/redis-socketio.error.log
user=iicc2
directory=/home/iicc2/umrah-mgmt/sites
startretries=10

[program:umrah-mgmt-node-socketio]
command=/home/iicc2/.nvm/versions/node/v20.20.2/bin/node /home/iicc2/umrah-mgmt/apps/frappe/socketio.js
priority=4
autostart=true
autorestart=true
stdout_logfile=/home/iicc2/umrah-mgmt/logs/node-socketio.log
stderr_logfile=/home/iicc2/umrah-mgmt/logs/node-socketio.error.log
user=iicc2
directory=/home/iicc2/umrah-mgmt
startretries=10

[group:umrah-mgmt-web]
programs=umrah-mgmt-umrah-web,umrah-mgmt-node-socketio

[group:umrah-mgmt-workers]
programs=umrah-mgmt-umrah-schedule,umrah-mgmt-umrah-short-worker,umrah-mgmt-umrah-long-worker

[group:umrah-mgmt-redis]
programs=umrah-mgmt-redis-cache,umrah-mgmt-redis-queue,umrah-mgmt-redis-socketio
