; Notes:
; priority=1 --> Lower priorities indicate programs that start first and shut down last
; killasgroup=true --> send kill signal to child processes too

; graceful timeout should always be lower than stopwaitsecs to avoid orphan gunicorn workers.
[program:business-mgm-umrah-web]
command=/home/iicc2/business-mgm/env/bin/gunicorn -b 127.0.0.1:8000 -w 9 --max-requests 5000 --max-requests-jitter 500 -t 120 --graceful-timeout 30 frappe.app:application --preload
priority=4
autostart=true
autorestart=true
stdout_logfile=/home/iicc2/business-mgm/logs/web.log
stderr_logfile=/home/iicc2/business-mgm/logs/web.error.log
stopwaitsecs=40
killasgroup=true
user=iicc2
directory=/home/iicc2/business-mgm/sites
startretries=10

[program:business-mgm-umrah-schedule]
command=/home/iicc2/.local/bin/bench schedule
priority=3
autostart=true
autorestart=true
stdout_logfile=/home/iicc2/business-mgm/logs/schedule.log
stderr_logfile=/home/iicc2/business-mgm/logs/schedule.error.log
user=iicc2
directory=/home/iicc2/business-mgm
startretries=10

[program:business-mgm-umrah-short-worker]
command=/home/iicc2/.local/bin/bench worker --queue short,default
priority=4
autostart=true
autorestart=true
stdout_logfile=/home/iicc2/business-mgm/logs/worker.log
stderr_logfile=/home/iicc2/business-mgm/logs/worker.error.log
user=iicc2
stopwaitsecs=360
directory=/home/iicc2/business-mgm
killasgroup=true
numprocs=1
process_name=%(program_name)s-%(process_num)d
startretries=10

[program:business-mgm-umrah-long-worker]
command=/home/iicc2/.local/bin/bench worker --queue long,default,short
priority=4
autostart=true
autorestart=true
stdout_logfile=/home/iicc2/business-mgm/logs/worker.log
stderr_logfile=/home/iicc2/business-mgm/logs/worker.error.log
user=iicc2
stopwaitsecs=1560
directory=/home/iicc2/business-mgm
killasgroup=true
numprocs=1
process_name=%(program_name)s-%(process_num)d
startretries=10

[program:business-mgm-redis-cache]
command=/usr/bin/redis-server /home/iicc2/business-mgm/config/redis_cache.conf
priority=1
autostart=true
autorestart=true
stdout_logfile=/home/iicc2/business-mgm/logs/redis-cache.log
stderr_logfile=/home/iicc2/business-mgm/logs/redis-cache.error.log
user=iicc2
directory=/home/iicc2/business-mgm/sites
startretries=10

[program:business-mgm-redis-queue]
command=/usr/bin/redis-server /home/iicc2/business-mgm/config/redis_queue.conf
priority=1
autostart=true
autorestart=true
stdout_logfile=/home/iicc2/business-mgm/logs/redis-queue.log
stderr_logfile=/home/iicc2/business-mgm/logs/redis-queue.error.log
user=iicc2
directory=/home/iicc2/business-mgm/sites
startretries=10

[program:business-mgm-redis-socketio]
command=/usr/bin/redis-server /home/iicc2/business-mgm/config/redis_socketio.conf
priority=1
autostart=true
autorestart=true
stdout_logfile=/home/iicc2/business-mgm/logs/redis-socketio.log
stderr_logfile=/home/iicc2/business-mgm/logs/redis-socketio.error.log
user=iicc2
directory=/home/iicc2/business-mgm/sites
startretries=10

[program:business-mgm-node-socketio]
command=/home/iicc2/.nvm/versions/node/v20.20.2/bin/node /home/iicc2/business-mgm/apps/frappe/socketio.js
priority=4
autostart=true
autorestart=true
stdout_logfile=/home/iicc2/business-mgm/logs/node-socketio.log
stderr_logfile=/home/iicc2/business-mgm/logs/node-socketio.error.log
user=iicc2
directory=/home/iicc2/business-mgm
startretries=10

[group:business-mgm-web]
programs=business-mgm-umrah-web,business-mgm-node-socketio

[group:business-mgm-workers]
programs=business-mgm-umrah-schedule,business-mgm-umrah-short-worker,business-mgm-umrah-long-worker

[group:business-mgm-redis]
programs=business-mgm-redis-cache,business-mgm-redis-queue,business-mgm-redis-socketio
